const RATE_LIMIT_POLICIES = {
	GLOBAL: "GLOBAL",
	AUTH_LOGIN: "AUTH_LOGIN",
	AUTH_REGISTER_REQUEST: "AUTH_REGISTER_REQUEST",
	AUTH_REGISTER_CONFIRM_TOKEN: "AUTH_REGISTER_CONFIRM_TOKEN",
	AUTH_PASSWORD_RESET: "AUTH_PASSWORD_RESET",
	AUTH_EMAIL_VERIFY: "AUTH_EMAIL_VERIFY",
	API_HEAVY: "API_HEAVY",
} as const;

export const POLICY_GLOBAL = RATE_LIMIT_POLICIES.GLOBAL;
export const POLICY_AUTH_LOGIN = RATE_LIMIT_POLICIES.AUTH_LOGIN;
export const POLICY_AUTH_REGISTER = RATE_LIMIT_POLICIES.AUTH_REGISTER_REQUEST;
export const POLICY_AUTH_REGISTER_CONFIRM_TOKEN = RATE_LIMIT_POLICIES.AUTH_REGISTER_CONFIRM_TOKEN;
export const POLICY_AUTH_PASSWORD_RESET = RATE_LIMIT_POLICIES.AUTH_PASSWORD_RESET;
export const POLICY_AUTH_EMAIL_VERIFY = RATE_LIMIT_POLICIES.AUTH_EMAIL_VERIFY;
export const POLICY_API_HEAVY = RATE_LIMIT_POLICIES.API_HEAVY;

export const RATE_LIMIT_POLICIES_KEY = "RATE_LIMIT_POLICIES";
export const NO_THROTTLE_KEY = "NO_THROTTLE";

export type RateLimitPolicyName = (typeof RATE_LIMIT_POLICIES)[keyof typeof RATE_LIMIT_POLICIES];
