app:
  name: "Linkdead"
  version: "v1"

server:
  port: 5000
  trustProxy: true
  allowedCorsOrigins:
    - "http://10.11.200.229:4000" # * use host machine IP with exposed port
    - "http://localhost:4000"
    - "http://127.0.0.1:4000"
  apiPathPrefix: "api"
  docsPathPrefix: "docs"

client:
  registerVerifyEmailPath: "auth/register/finalize"

logger:
  engine: "Winston"
  level: "info"
  dir: "logs"
  activeLogFiles: true

database:
  engine: "PostgreSQL"

redis:
  engine: "IORedis"
  appDb: 0
  appKeyPrefix: "linkdead_prod"
  jobsDb: 1
  jobsKeyPrefix: "linkdead_prod_jobs"

mailer:
  engine: "Nodemailer"
  host: "smtp.gmail.com"
  fromSupport: "Linkdead <support@arakotom.com>"
  fromNoReply: "Linkdead <noreply@arakotom.com>"
  templatesDir: "./dist/src/core/infra/mailer/adapters/templates"

rateLimiter:
  engine: "Throttler"
  policies:
    - name: "GLOBAL"
      ttlSec: 60
      limit: 300
    - name: "AUTH_LOGIN"
      ttlSec: 900
      limit: 10
    - name: "AUTH_REGISTER_REQUEST"
      ttlSec: 3600
      limit: 5
    - name: "AUTH_REGISTER_VERIFY_TOKEN_EMAIL"
      ttlSec: 600
      limit: 5
    - name: "AUTH_PASSWORD_RESET"
      ttlSec: 900
      limit: 3
    - name: "AUTH_REFRESH_TOKEN"
      ttlSec: 300
      limit: 5
    - name: "API_HEAVY"
      ttlSec: 60
      limit: 20

auth:
  registration:
    tokenTtlSec: 3600
    tokenCooldown:
      ttlSec: 1800
      maxAttempts: 5

jwt:
  accessTokenKey: "11nkd34d_4cc355_70k3n"
  refreshTokenKey: "11nkd34d_r3fr35h_70k3n"
  accessTokenTtlSec: 900
  refreshTokenTtlSec: 604800
