app:
  name: "Linkdead"
  version: "v1"

server:
  host: "localhost"
  port: 5001
  trustProxy: false
  allowedCorsOrigins:
    - "http://localhost:3000"
  apiPathPrefix: "api:prod"
  docsPathPrefix: "docs:prod"

logger:
  engine: "Winston"
  level: "debug"
  dir: "logs"
  activeLogFiles: false

database:
  engine: "PostgreSQl"

redis:
  engine: "IORedis"
  appDb: 0
  appKeyPrefix: "linkdead_prod"
  jobsDb: 1
  jobsKeyPrefix: "linkdead_prod_jobs"

mailer:
  engine: "Nodemailer"
  host: "smtp.gmail.com"
  fromSupport: "Linkdead <support@arakotom.com>"
  fromNoReply: "Linkdead <noreply@arakotom.com>"
  templatesDir: "src/core/infra/mailer/adapters/templates"
