app:
  name: "Linkdead"
  version: "v1"
  mode: "development"

server:
  port: 5000
  trustProxy: false
  allowedCorsOrigins:
    - "*"
  apiPrefix: "dev:api"
  docsPrefix: "dev:docs"

logger:
  level: "verbose"
  dir: "./logs"
  activeFiles: false

database:
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "arakotom"
  password: "arakotom"
  database: "linkdead_dev"
