app:
  name: "Linkdead"
  version: "v1"

server:
  port: 5000
  trustProxy: false
  allowedCorsOrigins:
    - "http://localhost:4000"
    - "http://127.0.0.1:4000"
  apiPathPrefix: "api"
  docsPathPrefix: "docs"

client:
  registerVerifyEmailPath: "auth/register/finalize"

logger:
  engine: "Winston"
  level: "verbose"
  dir: "logs"
  activeLogFiles: false

database:
  engine: "PostgreSQL"

redis:
  engine: "IORedis"
  appDb: 0
  appKeyPrefix: "linkdead_dev"
  jobsDb: 1
  jobsKeyPrefix: "linkdead_dev_jobs"

mailer:
  engine: "Nodemailer"
  host: "smtp.gmail.com"
  fromSupport: "Linkdead <support@arakotom.com>"
  fromNoReply: "Linkdead <noreply@arakotom.com>"
  templatesDir: "./src/core/infra/mailer/adapters/templates"

rateLimiter:
  engine: "Throttler"
  policies:
    - name: "GLOBAL"
      ttlSec: 15
      limit: 200
    - name: "AUTH_LOGIN"
      ttlSec: 15
      limit: 20
    - name: "AUTH_REGISTER_REQUEST"
      ttlSec: 15
      limit: 10
    - name: "AUTH_REGISTER_VERIFY_TOKEN_EMAIL"
      ttlSec: 15
      limit: 5
    - name: "AUTH_PASSWORD_RESET"
      ttlSec: 15
      limit: 10
    - name: "AUTH_EMAIL_VERIFY"
      ttlSec: 15
      limit: 15
    - name: "API_HEAVY"
      ttlSec: 15
      limit: 30

auth:
  registration:
    tokenTtlSec: 1800
    tokenCooldown:
      ttlSec: 600
      maxAttempts: 3

jwt:
  accessTokenKey: "linkdead_dev_access_token"
  refreshTokenKey: "linkdead_dev_refresh_token"
  accessTokenTtlSec: 900
  refreshTokenTtlSec: 604800
