app:
  name: "Linkdead"
  version: "v1"

server:
  port: 5000
  trustProxy: true
  allowedCorsOrigins:
    - "https://10.11.200.229:4000" # * for docker, use host machine IP with exposed port
  apiPathPrefix: "api"
  docsPathPrefix: "docs"

client:
  registerVerifyEmailPath: "auth/verify-email"

logger:
  engine: "Winston"
  level: "debug"
  dir: "logs"
  activeLogFiles: false

database:
  engine: "PostgreSQL"

redis:
  engine: "IORedis"
  appDb: 0
  appKeyPrefix: "linkdead_docker"
  jobsDb: 1
  jobsKeyPrefix: "linkdead_docker_jobs"

mailer:
  engine: "Nodemailer"
  host: "smtp.gmail.com"
  fromSupport: "Linkdead <support@arakotom.com>"
  fromNoReply: "Linkdead <noreply@arakotom.com>"
  templatesDir: "./dist/src/core/infra/mailer/adapters/templates"

rateLimiter:
  engine: "Throttler"
  policies:
    - name: "GLOBAL"
      ttlSec: 60
      limit: 300
    - name: "AUTH_LOGIN"
      ttlSec: 900
      limit: 10
    - name: "AUTH_REGISTER"
      ttlSec: 3600
      limit: 5
    - name: "AUTH_PASSWORD_RESET"
      ttlSec: 900
      limit: 3
    - name: "AUTH_EMAIL_VERIFY"
      ttlSec: 300
      limit: 5
    - name: "API_HEAVY"
      ttlSec: 60
      limit: 20

auth:
  registration:
    tokenTtlSec: 1800
    tokenCooldown:
      ttlSec: 600
      maxAttempts: 3